name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at the start of 12am and 12pm
    - cron: '0 */12 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LANGUAGE: "True"
          SHOW_COMMIT: "True"
          SHOW_TIMEZONE: "True" 
          SHOW_DAYS_OF_WEEK: "False" 
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
